# Release Configuration
project_name: waku
report_sizes: true

version: 2

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

universal_binaries:
  - replace: false

# Lets disable this for now and follow goreleaser upstream https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L67
# upx:
#   - ids: [default]
#     enabled: true
#     compress: best
#     lzma: true
#     brute: true
#     goos: [linux, windows] # skip darwin (macOS 13.x Ventura is not support now)
#     goarch: [amd64, arm64]

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: manpages/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

aurs:
  - name: waku-bin
    homepage: https://github.com/caffeine-addictt/waku
    description: A simple template repository generator. Lets make starting new proejcts feel like a breeze again!
    maintainers:
      - Jun Xiang <contact@ngjx.org>
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    license: AGPL-3.0
    git_url: "ssh://aur@aur.archlinux.org/waku-bin.git"
    skip_upload: false
    depends:
      - git
    package: |-
      # bin
      install -Dm755 "./waku" -t "$pkgdir/usr/bin"

      # license
      install -Dm644 "./LICENSE" "$pkgdir/usr/share/licenses/waku"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/waku.bash" "$pkgdir/usr/share/bash-completion/completions/waku"
      install -Dm644 "./completions/waku.zsh" "$pkgdir/usr/share/zsh/site-functions/_waku"
      install -Dm644 "./completions/waku.fish" "$pkgdir/usr/share/fish/vendor_completions.d/waku.fish"

      # man page
      mkdir -p "$pkgdir/usr/share/man/man1"
      install -Dm644 "./manpages/waku.1.gz" "$pkgdir/usr/share/man/man1/waku.1.gz"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    url_template: "https://github.com/caffeine-addictt/waku/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

dockers:
  - image_templates:
      - "caffeinec/waku:{{ .Tag }}-amd64"
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-amd64"
    skip_push: false
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/caffeine-addictt/waku/main/README.md"
      - "--label=io.artifacthub.package.logo-url=https://raw.githubusercontent.com/caffeine-addictt/waku/main/assets/logo.png"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Jun Xiang","email":"contact@ngjx.org"}]'
      - "--label=io.artifacthub.package.license=AGPL-3.0"
      - "--label=org.opencontainers.image.description=A simple template repository generator. Lets make starting new proejcts feel like a breeze again!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

  - image_templates:
      - "caffeinec/waku:{{ .Tag }}-arm64"
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-arm64"
    skip_push: false
    dockerfile: Dockerfile.release
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/caffeine-addictt/waku/main/README.md"
      - "--label=io.artifacthub.package.logo-url=https://raw.githubusercontent.com/caffeine-addictt/waku/main/assets/logo.png"
      - '--label=io.artifacthub.package.maintainers=[{"name":"Jun Xiang","email":"contact@ngjx.org"}]'
      - "--label=io.artifacthub.package.license=AGPL-3.0"
      - "--label=org.opencontainers.image.description=A simple template repository generator. Lets make starting new proejcts feel like a breeze again!"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "caffeinec/waku:{{ .Tag }}"
    image_templates:
      - "caffeinec/waku:{{ .Tag }}-amd64"
      - "caffeinec/waku:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/caffeine-addictt/waku:{{ .Tag }}"
    image_templates:
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-amd64"
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-arm64"

  - name_template: "{{ if not .Prerelease }}caffeinec/waku:latest{{ end }}"
    image_templates:
      - "caffeinec/waku:{{ .Tag }}-amd64"
      - "caffeinec/waku:{{ .Tag }}-arm64"
  - name_template: "{{ if not .Prerelease }}caffeinec/waku:v{{ .Major }}{{ end }}"
    image_templates:
      - "caffeinec/waku:{{ .Tag }}-amd64"
      - "caffeinec/waku:{{ .Tag }}-arm64"

  - name_template: "{{ if not .Prerelease }}ghcr.io/caffeine-addictt/waku:latest{{ end }}"
    image_templates:
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-amd64"
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-arm64"
  - name_template: "{{ if not .Prerelease }}ghcr.io/caffeine-addictt/waku:v{{ .Major }}{{ end }}"
    image_templates:
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-amd64"
      - "ghcr.io/caffeine-addictt/waku:{{ .Tag }}-arm64"

nfpms:
  - maintainer: Jun Xiang <contact@ngjx.org>
    description: A simple template repository generator. Lets make starting new proejcts feel like a breeze again!
    homepage: "https://github.com/caffeine-addictt/waku"
    license: AGPL-3.0
    formats: [rpm, apk, termux.deb, deb, archlinux]
    dependencies: [git]

brews:
  - homepage: "https://github.com/caffeine-addictt/waku"
    license: "AGPL-3.0"
    skip_upload: auto
    directory: Formula/waku
    repository:
      owner: caffeine-addictt
      name: homebrew-tap
      branch: "waku"
      token: "{{ .Env.GITHUB_PAT }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "A simple template repository generator. Lets make starting new proejcts feel like a breeze again!"
    dependencies:
      - git
    test: |
      system "#{bin}/waku version"
    extra_install: |-
      bash_completion.install "completions/waku.bash" => "waku"
      zsh_completion.install "completions/waku.zsh" => "_waku"
      fish_completion.install "completions/waku.fish"
      man1.install "manpages/waku.1.gz"

# chocolateys:
#   - name: waku
#     title: Waku
#     owners: caffeine-addictt
#     authors: caffeine-addictt
#     project_url: https://github.com/caffeine-addictt/waku
#     package_source_url: https://github.com/caffeine-addictt/waku
#     url_template: "https://github.com/caffeine-addictt/waku/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     icon_url: "https://raw.githubusercontent.com/caffeine-addictt/waku/main/assets/logo.png"
#     copyright: 2024 Jun Xiang
#     license_url: https://github.com/caffeine-addictt/waku/blob/main/LICENSE
#     require_license_acceptance: false
#     docs_url: https://github.com/caffeine-addictt/waku/blob/main/README.md
#     bug_tracker_url: https://github.com/caffeine-addictt/waku/issues
#     tags: "repository git generator simple quick quickstart template project project-generator cli command-line go"
#     summary: "A simple template repository generator."
#     description: A simple template repository generator. Lets make starting new proejcts feel like a breeze again!
#     release_notes: "https://github.com/caffeine-addictt/waku/releases/tag/{{ .Tag }}"
#     dependencies:
#       - id: git
#     api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
#     source_repo: "https://push.chocolatey.org/"
#     skip_publish: false

# snapcrafts:
#   - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
#     summary: Let's make starting new projects feel like a breeze again.
#     description: |
#       A simple template repository generator.
#       Lets make starting new proejcts feel like a breeze again!
#     license: AGPL-3.0
#     grade: stable
#     confinement: classic
#     publish: true

scoops:
  - repository:
      owner: caffeine-addictt
      name: scoop-bucket
      token: "{{ .Env.GITHUB_PAT }}"
    skip_upload: auto
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: bucket
    homepage: https://github.com/caffeine-addictt/waku
    description: A simple template repository generator. Lets make starting new proejcts feel like a breeze again!
    license: AGPL-3.0

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - --yes

release:
  ids: [default]
  draft: false
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"
  prerelease: auto
  mode: replace
  skip_upload: false

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - "^(T|t)ypo"
  groups:
    - title: Features
      regexp: '^.*?(F|f)eat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?(F|f)ix(\(.+\))??!?:.+$'
      order: 1
    - title: Improvements
      regexp: '^.*?((D|d)ocs?|(S|s)tyle|(T|t)est|(B|b)uild|(P|p)erf|(R|r)efactor)(\(.+\))??!?:.+$'
      order: 2
    - title: Security issues
      regexp: ^.*?(S|s)ecurity.*?$
      order: 4
    - title: Others
      order: 999
