FROM alpine:3.21.3
WORKDIR /app

# Install git
RUN apk add --update --no-cache git tini

# Add waku binaries
COPY waku_*.apk /tmp/
RUN apk add --no-cache --allow-untrusted /tmp/waku_*.apk

RUN adduser -D waku
USER waku


# Run
ENTRYPOINT ["/sbin/tini", "--", "waku"]
