name: Run Test Suite

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # This test suite will run for every language version for every OS defined in the matrix
  tests-os-matrix:
    name: "${{ matrix.language_version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        # Place your language versions you want to test
        language_version: ["v1.0.0", "v2.0.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup your language (This is specific to each language)
      # - name: Set up language ${{ matrix.language_version }}
      #   uses: actions/setup-python@v5
      #   with:
      #     language-version: ${{ matrix.language_version }}

      - name: Install dependencies
        run: |
          set -xe
          echo "Installed dependencies"
          # python -m pip install -r requirements.txt (for example)

      - name: Build project
        run: |
          set -xe
          echo "Building"
          # Place your code to build your project here

      - name: Testing
        run: |
          set -xe
          echo "Testing project"
          # Place your code to test your project here

  # This test will run once
  tests:
    name: "Testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup your language (This is specific to each language)
      # - name: Set up language ${{ matrix.language_version }}
      #   uses: actions/setup-python@v5
      #   with:
      #     language-version: ${{ matrix.language_version }}

      - name: Install dependencies
        run: |
          set -xe
          echo "Installed dependencies"
          # python -m pip install -r requirements.txt (for example)

      - name: Build project
        run: |
          set -xe
          echo "Building"
          # Place your code to build your project here

      - name: Testing
        run: |
          set -xe
          echo "Testing project"
          # Place your code to test your project here

  # It is recommended to require this check to pass before merging a pull request
  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [tests-os-matrix, tests]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
